### ISSUE TITLE
Progress indication

### ISSUE THREAD

**Issue by waldyrious** [mpetroff/color-cycle-survey#2]
During the survey it would be nice to see a progress bar or count of done/to do sets.

**Comment by mpetroff** [comment]
There's an existing count of the number of picks in the top right corner. As currently configured, the survey is open ended, so a "to do" count isn't really applicable. Adding a progress bar to 20 or 25 picks may be a good idea, however, since it may encourage more responses (currently, people are averaging ~10 picks per session).

**Comment by waldyrious** [comment]
Yeah, I realized that the survey was endless after opening this issue. I think perhaps some indication (other than at the opening instructions) that one can quit at any time would be helpful.

It could show a confirmation dialog explaining that the more picks the better, but at least people who missed that detail won't be left wondering how much more there is to go, and feeling like that they've failed to "complete" the survey whenever they decide to stop.

**Comment by mpetroff** [comment]
I clarified things a bit in ec1f6fc7fa7d01bb8921ebc043234d3b97a8cba5. Now the pick counter in the top right corner shows that it's infinite, and a reminder that one is free to stop at any time is shown after 10 picks, 25 picks, and every additional 25 picks.

**Comment by waldyrious** [comment]
That makes things sufficiently clear to me, thanks! As far as I'm concerned, this issue can be closed, unless you plan on improving the UI further.
